overrides:
  '@types/node': '^26'
  nodemailer: '^9'
  glob: npm:tinyglobby@latest

neverBuiltDependencies: []

minimumReleaseAge: 720
minimumReleaseAgeExclude:
  - '@atproto/*'
  - '@bsky.app/*'
  - '@atproto-labs/*'

allowBuilds:
  better-sqlite3: true
  core-js: true
