overrides:
  '@types/node': '^24'
  undici: '^7'
  nodemailer: '^8'
  glob: '^13'
  node-abi: '^4'
  bn.js: '^5'

neverBuiltDependencies: []

minimumReleaseAge: 720
minimumReleaseAgeExclude:
  - '@atproto/*'
  - '@bsky.app/*'
  - '@atproto-labs/*'

allowBuilds:
  better-sqlite3: true
  core-js: true
